# Generated by Django 4.2 on 2023-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipient', models.CharField(max_length=255)),
                ('phone_number_recipient', models.CharField(max_length=20)),
                ('email_recipient', models.EmailField(blank=True, max_length=254)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('congratulation', models.TextField(default='Поздравляю!!!')),
                ('name_payer', models.CharField(max_length=255)),
                ('phone_number_payer', models.CharField(max_length=20)),
                ('email_payer', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
