# Generated by Django 4.2 on 2023-05-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
