# Generated by Django 4.2 on 2023-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
