# Generated by Django 4.2 on 2023-05-17 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_certificate_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='phone_number_payer',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Не корректный номер телефона', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='phone_number_recipient',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Не корректный номер телефона', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
