# Generated by Django 4.2 on 2023-05-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский'), (3, 'Унисекс')], default=3, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
