# Generated by Django 4.2 on 2023-05-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_color_options_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='store.color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_title_img', verbose_name='Заголовочное фото'),
        ),
    ]
