# Generated by Django 4.2 on 2023-05-20 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_quantity_in_stock_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name_payer',
            field=models.CharField(max_length=255, verbose_name='Имя отправителя'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name_recipient',
            field=models.CharField(max_length=255, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='phone_number_payer',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Не корректный номер телефона', regex='^((8|\\+374|\\+994|\\+995|\\+375|\\+7|\\+380|\\+38|\\+996|\\+998|\\+993)[\\- ]?)?\\(?\\d{3,5}\\)?[\\- ]?\\d{1}[\\- ]?\\d{1}[\\- ]?\\d{1}[\\- ]?\\d{1}[\\- ]?\\d{1}(([\\- ]?\\d{1})?[\\- ]?\\d{1})?$')], verbose_name='Номер отправителя'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='L', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
