# Generated by Django 4.2 on 2023-05-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_favorite_alter_size_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
