# Generated by Django 4.2 on 2023-05-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
