# Generated by Django 4.2 on 2023-05-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_certificate_user_user_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='user.certificate'),
        ),
    ]
