# Generated by Django 4.2 on 2023-05-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='certificate',
        ),
    ]
